spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB # 파일 최대 크기 100 MB
      max-request-size: 100MB # 파일 최대 요청 크기 100 MB

  datasource:
    url: jdbc:mysql://localhost:3306/shareu?useSSL=false&useUnicode=true&autoReconnect=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #      show_sql: true
        format_sql: true
    open-in-view: false

  jwt:
    secret: inu-appcenter

cloud:
  aws:
    s3:
      bucket: shareu-file
    region:
      static: ap-northeast-2
    stack:
      auto: false

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace