spring:
  mail:
    host: smtp.gmail.com # smtp Gmail 설정
    port: 587  # smtp 포트 설정
    username: juwom0831@gmail.com # 구글 아이디
    password: rjatjd0815* # 비밀번호
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB # 파일 최대 크기 100 MB
      max-request-size: 100MB # 파일 최대 요청 크기 100 MB
      location: /Users/juhwan/temp/ # 파일 저장 위치 MAC 기준

  datasource:
    url: jdbc:mysql://localhost:3306/shareu?useSSL=false&useUnicode=true&autoReconnect=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #      show_sql: true
        format_sql: true
    open-in-view: false

  jwt:
    secret: inu-appcenter

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace